#! /bin/sh

localize -m -l de -f de-gallery.sdf
localize -m -l de -f de-patches.sdf
localize -m -l es -f es-gallery.sdf
localize -m -l es -f es-patches.sdf
localize -m -l fi -f fi-gallery.sdf
localize -m -l fi -f fi-patches.sdf
localize -m -l fr -f fr-gallery.sdf
localize -m -l fr -f fr-patches.sdf
localize -m -l hu -f hu_az.sdf
localize -m -l hu -f hu-gallery.sdf
localize -m -l hu -f hu-patches.sdf
localize -m -l it -f it-gallery.sdf
localize -m -l it -f it-patches.sdf
localize -m -l ja -f ja-gallery.sdf
localize -m -l ja -f ja-patches.sdf
localize -m -l ka -f GSI_ka.sdf
localize -m -l ka -f ka-gallery.sdf
localize -m -l ka -f ka-patches.sdf
localize -m -l nl -f nl-gallery.sdf
localize -m -l nl -f nl-patches.sdf
localize -m -l pl -f pl-gallery.sdf
localize -m -l pl -f pl-patches.sdf
localize -m -l pt-BR -f pt-BR-gallery.sdf
localize -m -l pt-BR -f pt-BR-patches.sdf
localize -m -l tr -f tr-gallery.sdf
localize -m -l tr -f tr-patches.sdf
localize -m -l zh-CN -f zh-CN-gallery.sdf
localize -m -l zh-CN -f zh-CN-patches.sdf
localize -m -l en-US -f ooopteam.sdf