@ECHO OFF
ECHO [+] Remove TEMP...
RD /S /Q _TEMP_
FOR %%T IN (educate finance forms layout misc officorr offimisc personal presnt) DO CALL cretwork.bat %%T %1
ECHO [+] Remove OOOP-templates-%1.oxt...
DEL OOOP-templates-%1.oxt
ECHO [+] Creating empty OOOP-templates-%1.oxt...
COPY TemplatePackage.oxt OOOP-templates-%1.oxt 
ECHO [+] Compressing to OOOP-templates-%1.oxt...
7Z.EXE A -MX=9 -R OOOP-templates-%1.oxt .\_TEMP_\*
ECHO [+] Remove TEMP...
RD /S /Q _TEMP_
ECHO [+] Finished, exiting and go home...
ECHO.