@ECHO OFF
ECHO [+] Remove TEMP...
RD /S /Q _TEMP_
ECHO [+] Remove OOOP-gallery.oxt...
DEL OOOP-gallery.oxt
ECHO [+] Creating empty OOOP-gallery.oxt...
COPY GalleryPackage.oxt OOOP-gallery.oxt 
MD .\_TEMP_\gallery
XCOPY ..\..\extras\source\gallery\accessories\*.* .\_TEMP_\gallery\ /S /EXCLUDE:cregal.exc
ECHO [+] Compressing to OOOP-gallery.oxt...
7Z.EXE A -MX=9 -R OOOP-gallery.oxt .\_TEMP_\*
ECHO [+] Finished, exiting and go home...
ECHO.